name: Sync Financial And Data Skills

on:
  push:
    branches:
      - main

jobs:
  sync-trend-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout  repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@aisa.one"

      - name: Clone trend-forecast
        env:
          TOKEN: ${{ secrets.SYNC_AISAS_KILLS_TOKEN  }}
        run: |
          git clone https://x-access-token:${TOKEN}@github.com/AIsa-team/agent-skills.git target-repo

      - name: Sync trend-forecast into Financial And Data Repo
        run: |
          rm -rf target-repo/trend-forecast
          mkdir -p target-repo/trend-forecast

          cp -a trend-forecast/. target-repo/trend-forecast/

          echo "Target trend-forecast:"
          ls -la target-repo/trend-forecast
          find trend-forecast -type f

      - name: Commit and push to Financial And Data Repo
        env:
          TOKEN: ${{ secrets.SYNC_AISAS_KILLS_TOKEN  }}
        run: |
          cd target-repo
          ls -l

          git status
          git add -A trend-forecast
          git status

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync trend-forecast folder"
            git push https://x-access-token:${TOKEN}@github.com/AISA-skills/financial-data-skills.git HEAD:main
          fi